[build-system]
requires = [
  "mpi4py>=3.0",
  "numpy>=1.15.0",
  "pybind11[global]>=2.6",
  "setuptools>=46.4.0",
  "wheel",
  "scikit-build>=0.13",
  "cmake",
  "ninja; platform_system!='Windows'",
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths = ["python_tests"]
